# Generated by Django 3.2 on 2024-03-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_working_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
