# Generated by Django 3.2 on 2024-03-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_profile_last_working_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
