# Generated by Django 3.2 on 2024-09-05 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leave_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
